### ISSUE TITLE
question!

### ISSUE THREAD

**Issue by yunchiri** [LoganWright/PlistModel#7]
what is instanceOfPlistModel?

could you show me code?

I can't understand how to use sample

thank you

**Comment by LoganWright** [comment]
Hi @yunchiri 

An instance of PlistModel is an in memory representation of the `.plist` file that loads, for example, when we have this:

```ObjC
[DynamicModel plistNamed:@"DynamicModel" inBackgroundWithBlock:^(PlistModel *plistModel) {
    NSLog(@"Fetched plist model: %@", plistModel);
}];
```

In the above example, the variable `plistModel` is an instance of the model that can be used and modified.  

You can also allocate in line like this:

```ObjC
MyPlist *plist = [MyPlist plistNamed:@"MyPlist"];
plist[@"key"] = @"value";
```

Where in the above, `plist` is a representation of your plist on disk.  I'm not exactly sure what you're looking for, does this answer your question?

**Comment by yunchiri** [comment]
Hi @LoganWright 

aha 
Now I understand

"instanceOfPlistModel" mean  just sudo code right?

thank you^^

**Comment by LoganWright** [comment]
yup!
